services:
  db:
    image: mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - person_db:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  person_db:
    driver: local
